"use client";
import {useEffect,useMemo,useState} from "react";
import {browserSupabase} from "@/lib/supabase-browser";
const blank={title:"",slug:"",excerpt:"",content:"",category:"Copyright Guides",tags:"",featured_image:"",seo_title:"",seo_description:"",source_help_url:"",status:"draft",featured:false,author_name:"CopyRaid Editorial"};
function slugify(v=""){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
export default function AdminPage(){
 const supabase=useMemo(()=>browserSupabase(),[]);const [ready,setReady]=useState(false);const [allowed,setAllowed]=useState(false);const [posts,setPosts]=useState([]);const [form,setForm]=useState(blank);const [editing,setEditing]=useState(null);const [message,setMessage]=useState("");const [uploading,setUploading]=useState(false);
 useEffect(()=>{boot()},[]);
 async function boot(){if(!supabase){setMessage("Supabase environment variables are missing.");setReady(true);return}const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.href="/admin/login";return}const {data:admin}=await supabase.from("blog_admins").select("user_id").eq("user_id",session.user.id).maybeSingle();if(!admin){setReady(true);setAllowed(false);return}setAllowed(true);await loadPosts();setReady(true)}
 async function loadPosts(){const {data,error}=await supabase.from("blog_posts").select("*").order("created_at",{ascending:false});if(error)setMessage(error.message);else setPosts(data||[])}
 function change(name,value){setForm(f=>({...f,[name]:value,...(name==="title"&&!editing&&!f.slug?{slug:slugify(value)}:{})}))}
 function edit(post){setEditing(post.id);setForm({...post,tags:(post.tags||[]).join(", ")});window.scrollTo({top:0,behavior:"smooth"})}
 function reset(){setEditing(null);setForm(blank)}
 async function save(e){e.preventDefault();setMessage("Saving…");const payload={title:form.title.trim(),slug:slugify(form.slug||form.title),excerpt:form.excerpt.trim(),content:form.content,category:form.category.trim(),tags:String(form.tags||"").split(",").map(x=>x.trim()).filter(Boolean),featured_image:form.featured_image||null,seo_title:form.seo_title||null,seo_description:form.seo_description||null,source_help_url:form.source_help_url||null,status:form.status,featured:!!form.featured,author_name:form.author_name||"CopyRaid Editorial",published_at:form.status==="published"?(form.published_at||new Date().toISOString()):null};const result=editing?await supabase.from("blog_posts").update(payload).eq("id",editing):await supabase.from("blog_posts").insert(payload);if(result.error){setMessage(result.error.message);return}setMessage("Saved.");reset();await loadPosts()}
 async function remove(id){if(!confirm("Delete this article permanently?"))return;const {error}=await supabase.from("blog_posts").delete().eq("id",id);if(error)setMessage(error.message);else await loadPosts()}
 async function uploadImage(file){if(!file)return;setUploading(true);const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=Date.now()+"-"+slugify(file.name.replace(/\.[^.]+$/,""))+"."+ext;const {error}=await supabase.storage.from("blog-images").upload(path,file,{upsert:false});if(error){setMessage(error.message);setUploading(false);return}const {data}=supabase.storage.from("blog-images").getPublicUrl(path);change("featured_image",data.publicUrl);setUploading(false)}
 async function signOut(){await supabase.auth.signOut();window.location.href="/admin/login"}
 if(!ready)return <div className="admin-loading">Loading CopyRaid Blog Admin…</div>;
 if(!allowed)return <section className="admin-auth"><div className="admin-auth-card"><h1>Access not authorized</h1><p>This signed-in account is not listed in <code>blog_admins</code>.</p><button onClick={signOut}>Sign out</button></div></section>;
 return <section className="admin-page"><div className="admin-top"><div><span className="eyebrow">CopyRaid Blog</span><h1>{editing?"Edit article":"New article"}</h1></div><div className="admin-actions"><a href="/" target="_blank">View blog ↗</a><button onClick={signOut}>Sign out</button></div></div>
 <form className="editor" onSubmit={save}><div className="editor-main"><label>Title<input required value={form.title} onChange={e=>change("title",e.target.value)} placeholder="Article headline"/></label><label>Slug<input required value={form.slug} onChange={e=>change("slug",e.target.value)} placeholder="article-url-slug"/></label><label>Excerpt<textarea rows="3" required value={form.excerpt} onChange={e=>change("excerpt",e.target.value)} placeholder="Short summary shown on cards and search results."/></label><label>Article content <span>Markdown supported</span><textarea className="content-editor" required value={form.content} onChange={e=>change("content",e.target.value)} placeholder={"## Heading\n\nWrite the article here…"}/></label></div>
 <aside className="editor-side"><div className="admin-panel"><h3>Publishing</h3><label>Status<select value={form.status} onChange={e=>change("status",e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label><label className="check"><input type="checkbox" checked={!!form.featured} onChange={e=>change("featured",e.target.checked)}/> Feature on homepage</label><button className="primary-button" type="submit">{editing?"Update article":"Save article"}</button>{editing&&<button type="button" onClick={reset}>Cancel edit</button>}{message&&<div className="form-message">{message}</div>}</div>
 <div className="admin-panel"><h3>Classification</h3><label>Category<input value={form.category} onChange={e=>change("category",e.target.value)}/></label><label>Tags<input value={form.tags||""} onChange={e=>change("tags",e.target.value)} placeholder="Instagram, DMCA, creators"/></label><label>Author<input value={form.author_name||""} onChange={e=>change("author_name",e.target.value)}/></label></div>
 <div className="admin-panel"><h3>Featured image</h3>{form.featured_image&&<img className="admin-preview" src={form.featured_image} alt=""/>}<input type="file" accept="image/*" onChange={e=>uploadImage(e.target.files?.[0])}/>{uploading&&<small>Uploading…</small>}<label>Or image URL<input value={form.featured_image||""} onChange={e=>change("featured_image",e.target.value)}/></label></div>
 <div className="admin-panel"><h3>SEO</h3><label>SEO title<input maxLength="70" value={form.seo_title||""} onChange={e=>change("seo_title",e.target.value)}/></label><label>Meta description<textarea maxLength="170" rows="4" value={form.seo_description||""} onChange={e=>change("seo_description",e.target.value)}/></label><label>Help Center source<input value={form.source_help_url||""} onChange={e=>change("source_help_url",e.target.value)} placeholder="https://help.copyraid.com/articles/..."/></label></div></aside></form>
 <div className="admin-list"><div className="section-heading"><div><span className="eyebrow">Content library</span><h2>{posts.length} articles</h2></div></div>{posts.map(p=><div className="admin-row" key={p.id}><div><span className={"status "+p.status}>{p.status}</span><strong>{p.title}</strong><small>/{p.slug} · {p.category}</small></div><div><button onClick={()=>edit(p)}>Edit</button><button className="danger" onClick={()=>remove(p.id)}>Delete</button></div></div>)}</div></section>
}
